name: Create Zip Artifact
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create Zip
      run: zip -r notifier.zip obsNativeNotifier obs_notify.py

    - uses: actions/upload-artifact@v3
      with:
        name: notifier-script
        path: notifier.zip
        
